# In this notebook, we are going to cover some of the most fundamental concepts of tensors using tensorflow

We are gong to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function(a way to speed up your normal python functions)
* Using GPUs with TensorFlow or TPUs
* Example excercises

## Introduction to Tensors

In [ ]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
# Creating Tensors with tf.constant()
scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor(ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Creating a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Check the dimension of our vector
vector.ndim

1

In [ ]:
# create a matrix (more than one dimension)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],[3.,2.,],[8.,9.]], dtype=tf.float16) #dtype specifies the datatype of tensor
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]
                      ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we created so far:
* Scaler : a single number
* Vector : a number with direction (eg: wind speed and direction)
* Matrix : a 2-dimentional array of numbers
* Tensor : an n-dimentional array of numbers( where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimentional tensor is a vector)


### Creating Tensors with `tf.Variable()`

In [ ]:
# Creating a tensor with tf.Variable() as above
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try to change an element in our changable tensor
changable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
#changable_tensor[0] = 7
# will give error

In [ ]:
# Trying with assign
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Let's try change our unchanagble tensor
unchangable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
# Trying with assign
#unchangable_tensor[0].assign(7)
# will give error

*NOTE* : Rarely in practice you need to use `tf.constant` or `tf.Variable`. Tensorflow will do it for you

### Creating random tensors

Random Tensors are tensors of some arbitrary size which contain random numbers

In [ ]:
# Create two random tensors (but same tensors)
random_1 = tf.random.Generator.from_seed(42) # Set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_1


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [ ]:
# shuffle a tensor(valuable when you want to shuffle your data so that the inherent data doesn't affect learning)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled.ndim

2

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# shuffle our non shuffle tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed.

Its interactions with operation-level seeds is as follows:

1. If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.
2. If the global seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.
3. If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.
4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [ ]:
# creaing some tensors

tf.random.set_seed(42)
tensor_1 = tf.constant(tf.random.uniform(shape=(3,3)))
tensor_1

tensor_2 = tf.constant(tf.random.normal(shape=(3,3), seed=42))


tensor_3 = tf.constant(tf.random.normal(shape=(3,3), seed=42))
tensor_1,tensor_2, tensor_3

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 ],
        [0.46448255, 0.03366041, 0.68467236],
        [0.74011743, 0.8724445 , 0.22632635]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 1.3148774 , -0.15421568,  0.9113878 ],
        [-0.7991441 , -0.10875294,  0.28436786],
        [ 0.7661625 , -0.6211289 ,  0.9974318 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 1.2668815 , -0.9484186 ,  0.10077834],
        [-0.6262223 ,  1.6540284 ,  1.0248556 ],
        [ 0.98768395,  1.399825  ,  0.58911043]], dtype=float32)>)

In [ ]:
# shuffling
tf.random.set_seed(42)
shuffled_1 = tf.random.shuffle(tensor_1)
shuffled_1, shuffled_1 == tensor_1


(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.46448255, 0.03366041, 0.68467236],
        [0.74011743, 0.8724445 , 0.22632635],
        [0.6645621 , 0.44100678, 0.3528825 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[False, False, False],
        [False, False, False],
        [False, False, False]])>)

### Other ways to make tensors

In [ ]:
# Creating tensor of ones
tf.ones(shape=(3,3,3))

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [ ]:
# Creating tensor of zeroes
tf.zeros(shape=(3,2,3))

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

### Turn NumPy Arrays into Tensors

The main difference between NumPy arrays and tenorflow is that tensors can be run on GPU in a much faster way.

In [ ]:
# You can also turn numpy arrays into tensors
import numpy as np

numpy_A = np.arange(1,25, dtype=np.int32) #create a numpy array with elements from 1 and 25
numpy_A

# X = tf.constant(some_matrix) Capital for matrix or tensor
# y = tf.constant(vector) small letter for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A,shape=(6,4))
A

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]], dtype=int32)>

In [ ]:
B = tf.constant(numpy_A)
B

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

### Getting information from Tensors

When dealing with tensors you probably want to be aware of the following attributes.
* Shape - tensor.shape
* Rank - tensor.ndim
* Axis or Dimension - tensor[0], tensor[:,1]...
* Size - tf.size(tensor)

In [ ]:
# Create a rank 4 tensor
rank_4_tensor = tf.zeros((2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape , rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of our tensor
print("DataType of every element : ",rank_4_tensor.dtype)
print("Number of dimensions : ",rank_4_tensor.ndim)
print("Shape of tensor : ",rank_4_tensor.shape)
print("Elements along the 0 axis : ",rank_4_tensor.shape[0])
print("Elements along the last axis : ",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor : ",tf.size(rank_4_tensor))
print("Total number of elements in our tensor : ",tf.size(rank_4_tensor).numpy())

DataType of every element :  <dtype: 'float32'>
Number of dimensions :  4
Shape of tensor :  (2, 3, 4, 5)
Elements along the 0 axis :  2
Elements along the last axis :  5
Total number of elements in our tensor :  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor :  120


### Indexing Tensors

Tensors can be indexed just like Python lists

In [ ]:
# Get the first 2 elements of each dimensions
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]


<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor
rank_2_tensor = tf.constant(np.arange(1,5), shape=(2,2))
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4]])>

In [ ]:
# Get the last item of each row of rank_2_tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 4])>

In [ ]:
# Adding in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int64, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]])>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) #means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int64, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]])>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0) # expand the 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int64, numpy=
array([[[1, 2],
        [3, 4]]])>

### Manipulating Tensors(tensor operations)

**Basic Operations**

`+ - * /`

In [ ]:
# You can add values into a tensor using addition opertor

tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
#original tensor
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Multiplication

tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# Subtraction

tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
# We can use tensorflow builtin function too
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tf.math.add(tensor,5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 12],
       [ 8,  9]], dtype=int32)>

In [ ]:
tf.math.subtract(tensor, 2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 5],
       [1, 2]], dtype=int32)>

In [ ]:
tf.math.divide(tensor,2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

### Matrix Multiplication(Tensor Multiplication)

In machine learning, matrix multiplication is one of the most tensor operations.

There are 2 rules the matrices need to fullfill if we are going to matrix multiply them.
1. The inner dimensions must match
2. The resulting matrix has the shape of outer dimension

In [ ]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Matrix multiplication with python using @ operator
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Example
matrix_One = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
matrix_Two = tf.constant([[3,5],[6,7],[1,8]])

matrix_One, matrix_Two

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [ ]:
tf.matmul(matrix_One, matrix_Two)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
tensor.shape

TensorShape([2, 2])

In [ ]:
X = tf.constant(np.arange(1,7), shape=(3,2))
Y = tf.constant(np.arange(7,13), shape=(3,2))
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int64, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [ ]:
X

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [ ]:
# Let's change the shape of Y
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [ ]:
# Try to multiply X with reshaped Y
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [ ]:
# Try reshaping X
tf.matmul(tf.reshape(X, shape=(2,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[ 58,  64],
       [139, 154]])>

In [ ]:
tf.reshape(X, shape=(2,3)).shape , Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [ ]:
# Can do the same with Transpose
X, tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int64, numpy=
 array([[1, 3, 5],
        [2, 4, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int64, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>)

In [ ]:
# Try matrix multiplication with transpose
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[ 89,  98],
       [116, 128]])>

**The dot product**
Matrix multiplication is also reffered to as dot product

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`


In [ ]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int64, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [ ]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X),Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[ 89,  98],
       [116, 128]])>

In [ ]:
# Perform matrix multiplication between X and Y(transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [ ]:
# Perform matrix multiplication between X and Y(reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [ ]:
# Check the values of Y, reshape Y and transposed Y
print("Normal : ")
print(Y,"\n")
print("Y reshaped to (2,3): ")
print(tf.reshape(Y,(2,3)),"\n")

print("Y transposed")
print(tf.transpose(Y))

Normal : 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int64) 

Y reshaped to (2,3): 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int64) 

Y transposed
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int64)


In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

**NOTE:** Generally when performing matrix multiplication on two tensors and one of the axes doesn't line up you will generally transpose rather than reshape one of the tensors to satisfy the matrix multiplication condition.

### Changing the datatype of a tensor

In [ ]:
# Changing a new tensor with default datatype(float32)
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [ ]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [ ]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# chnage from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [ ]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### Aggregating Tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.


In [ ]:
# Getting the absolute values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggreagation:
* Minumum of tensor
* Maximum of a tensor
* Mean of a tensor
* Sum of a tensor

In [ ]:
tf.random.set_seed(42)
new_Tensor = tf.constant(np.arange(1,21), shape=(5,4))
new_Tensor = tf.random.shuffle(new_Tensor)
new_Tensor

<tf.Tensor: shape=(5, 4), dtype=int64, numpy=
array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [17, 18, 19, 20],
       [13, 14, 15, 16],
       [ 5,  6,  7,  8]])>

In [ ]:
tf.random.set_seed(42)
new_Tensor2 = tf.constant(np.arange(21,1,-1), shape=(5,4))
new_Tensor2 = tf.random.shuffle(new_Tensor2)
new_Tensor2

<tf.Tensor: shape=(5, 4), dtype=int64, numpy=
array([[13, 12, 11, 10],
       [21, 20, 19, 18],
       [ 5,  4,  3,  2],
       [ 9,  8,  7,  6],
       [17, 16, 15, 14]])>

In [ ]:
#compairing 2 tensors for min
tf.math.minimum(new_Tensor, new_Tensor2)

<tf.Tensor: shape=(5, 4), dtype=int64, numpy=
array([[ 9, 10, 11, 10],
       [ 1,  2,  3,  4],
       [ 5,  4,  3,  2],
       [ 9,  8,  7,  6],
       [ 5,  6,  7,  8]])>

In [ ]:
# Compairing two tensors for max
tf.math.maximum(new_Tensor, new_Tensor2)

<tf.Tensor: shape=(5, 4), dtype=int64, numpy=
array([[13, 12, 11, 12],
       [21, 20, 19, 18],
       [17, 18, 19, 20],
       [13, 14, 15, 16],
       [17, 16, 15, 14]])>

In [ ]:
#computing the min of a tensor
tf.math.reduce_min(new_Tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
# computing the min of a tensor by keeping the dimension
tf.math.reduce_min(new_Tensor,keepdims=True)

<tf.Tensor: shape=(1, 1), dtype=int64, numpy=array([[1]])>

In [ ]:
# Finding the max of a tensor
tf.math.reduce_max(new_Tensor2)

<tf.Tensor: shape=(), dtype=int64, numpy=21>

In [ ]:
# Finding the max of a tensor by keeping dimensions
tf.math.reduce_max(new_Tensor2, keepdims=True)

<tf.Tensor: shape=(1, 1), dtype=int64, numpy=array([[21]])>

In [ ]:
#Finding the mean of a tensor
tf.math.reduce_mean(new_Tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=10>

In [ ]:
# finding the mean of tensor among axis1
tf.math.reduce_mean(new_Tensor, axis=1)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([10,  2, 18, 14,  6])>

In [ ]:
# finding the mean of tensor along axis 0
tf.math.reduce_mean(new_Tensor, axis=0)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([ 9, 10, 11, 12])>

In [ ]:
# Keeping the dimensions of original tensor when finding mean
tf.math.reduce_mean(new_Tensor, keepdims=True)

<tf.Tensor: shape=(1, 1), dtype=int64, numpy=array([[10]])>

In [ ]:
# finding the sum of elements in a tensor
tf.math.reduce_sum(new_Tensor2)

<tf.Tensor: shape=(), dtype=int64, numpy=230>

In [ ]:
# finding the sum of tensor along axis 0
tf.math.reduce_sum(new_Tensor2, axis=0)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([65, 60, 55, 50])>

In [ ]:
# finding the sum of tensor along axis1
tf.math.reduce_sum(new_Tensor2, axis=1)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([46, 78, 14, 30, 62])>

In [ ]:
# finding the sum of a tensor along axis 0 by keeping the dimensions
tf.math.reduce_sum(new_Tensor2, axis=0, keepdims=True)

<tf.Tensor: shape=(1, 4), dtype=int64, numpy=array([[65, 60, 55, 50]])>

In [ ]:
# converting the dtype of new_Tensor
copy_of_Tensor = tf.cast(new_Tensor, dtype=tf.float32)
copy_of_Tensor

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 9., 10., 11., 12.],
       [ 1.,  2.,  3.,  4.],
       [17., 18., 19., 20.],
       [13., 14., 15., 16.],
       [ 5.,  6.,  7.,  8.]], dtype=float32)>

**NOTE:** We can only compute variance and standard deviation on float type tensors

In [ ]:
# finding the variance
tf.math.reduce_variance(copy_of_Tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=33.25>

In [ ]:
# finding the variance across an axis 0
tf.math.reduce_variance(copy_of_Tensor, axis=0, keepdims=True)

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[32., 32., 32., 32.]], dtype=float32)>

In [ ]:
# finding the variance across axis 1
tf.math.reduce_variance(copy_of_Tensor, axis=1, keepdims=True)

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[1.25],
       [1.25],
       [1.25],
       [1.25],
       [1.25]], dtype=float32)>

In [ ]:
# finding the standard deviation of the tensor
tf.math.reduce_std(copy_of_Tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=5.766281>

**NOTE:** To convert a tensor to numpy array use `tensor.numpy()`

In [ ]:
new_Tensor.numpy()

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [17, 18, 19, 20],
       [13, 14, 15, 16],
       [ 5,  6,  7,  8]])

In [ ]:
#finding the std across axis 0, by keeping the dimensions
tf.math.reduce_std(copy_of_Tensor, axis=0, keepdims=True)

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[5.656854, 5.656854, 5.656854, 5.656854]], dtype=float32)>

In [ ]:
#finding the std across axis 1, by keeping the dimensions
tf.math.reduce_std(copy_of_Tensor, axis=1, keepdims=True)

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[1.118034],
       [1.118034],
       [1.118034],
       [1.118034],
       [1.118034]], dtype=float32)>

### Finding the positional maximum and positional minimum

In [ ]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# finding the positional max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# index on our largest postion value
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# finding the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor(removing all single  dimensions)

In [ ]:
# Create a tensor to get started
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
       dtype=float32)>,
 TensorShape([50]))

In [ ]:
G.ndim

5

In [ ]:
G_squeezed.ndim

1

### One-hot encoding Tensors



In [ ]:
# Create a list of indices
some_list = [0,1,2,3] # could be red, green, blue, purple

#Onehot encode our list of indices
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding

tf.one_hot(some_list,4, on_value="I love deep learning", off_value="I also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'I love deep learning']], dtype=object)>

### Squaring, Log and Squareroot

In [ ]:
# Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

**NOTE:** sqrt function of `tf.math.sqrt()` needs the tensor to be of float type

In [ ]:
# Square root
tf.math.sqrt(tf.cast(H, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
# finding the log
tf.math.log(tf.cast(H, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

TensorFlow interacts easily with numpy arrays

**NOTE**: Tensors can run on GPU or TPU where as numpy runs on CPU for faster processing

In [ ]:
# creae a tensor directly from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# convert our tensor back to arrray
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# The default type of each are slightly differrent
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10,])
#check the datatype of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPU's

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Mon Feb  5 02:08:47 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P8              13W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

> 🔑**NOTE:** If you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible