#Exercise
🛠 00 TensorFlow Fundamentals Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
2. Find the shape, rank and size of the tensors you created in
3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
7. Find the min and max values of the tensor you created in 6.
8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

In [ ]:
import numpy as np
import tensorflow as tf
# vector
vector_1 = tf.constant(np.arange(0,4))
vector_1

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([0, 1, 2, 3])>

In [ ]:
#scalar
scalar = tf.constant([1])
scalar

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>

In [ ]:
#matrix
matrix = tf.constant(np.arange(0,4), shape=(2,2))
matrix

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[0, 1],
       [2, 3]])>

In [ ]:
#tensor
tensor = tf.constant(np.arange(1,28), shape=(3,3,3))
tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int64, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])>

In [ ]:
# shapes of tensors
def find_shape_rank_size(copy_tensor):
  print(f"{copy_tensor}")
  print(f"Shape of tensor: {copy_tensor.shape} ")
  print(f"Dimensions : {copy_tensor.ndim}")
  print(f"Size : {tf.size(copy_tensor)}")
  print("\n")


find_shape_rank_size(vector_1)
find_shape_rank_size(scalar)
find_shape_rank_size(matrix)
find_shape_rank_size(tensor)

[0 1 2 3]
Shape of tensor: (4,) 
Dimensions : 1
Size : 4


[1]
Shape of tensor: (1,) 
Dimensions : 1
Size : 1


[[0 1]
 [2 3]]
Shape of tensor: (2, 2) 
Dimensions : 2
Size : 4


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Shape of tensor: (3, 3, 3) 
Dimensions : 3
Size : 27




In [ ]:
#random tensors
tf.random.set_seed(42)
tensor_A = tf.random.uniform(minval=0, maxval=1, shape=(5,300))

tensor_B = tf.random.uniform(minval=0, maxval=1, shape=(5,300))

find_shape_rank_size(tensor_A)
print("\n")
find_shape_rank_size(tensor_B)

[[0.6645621  0.44100678 0.3528825  ... 0.31410468 0.7593535  0.03699052]
 [0.532024   0.29129946 0.10571766 ... 0.54052293 0.31425726 0.2200619 ]
 [0.08404207 0.03614604 0.97732127 ... 0.21516645 0.9786098  0.00726748]
 [0.7396945  0.6653172  0.0787828  ... 0.7117733  0.07013571 0.9409125 ]
 [0.15861344 0.12024033 0.27218235 ... 0.8824879  0.1432488  0.44135118]]
Shape of tensor: (5, 300) 
Dimensions : 2
Size : 1500




[[0.68789124 0.48447883 0.9309944  ... 0.6920762  0.33180213 0.9212563 ]
 [0.27369928 0.10631859 0.6218617  ... 0.4382149  0.30427706 0.51477313]
 [0.00920248 0.37280262 0.8177401  ... 0.56786287 0.49201214 0.9892651 ]
 [0.88608265 0.08672249 0.12160683 ... 0.91770685 0.72545695 0.8280058 ]
 [0.36690474 0.9200133  0.9646884  ... 0.69012    0.7137332  0.2584542 ]]
Shape of tensor: (5, 300) 
Dimensions : 2
Size : 1500




In [ ]:
# product of matrix

tf.matmul(tensor_A, tf.reshape(tensor_B,shape=(300,5)))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[76.2758  , 79.17824 , 77.82306 , 79.38919 , 79.37956 ],
       [72.706345, 73.675156, 73.71575 , 74.184204, 73.72947 ],
       [75.74081 , 76.490845, 74.435486, 78.802124, 77.70212 ],
       [68.98616 , 75.53636 , 74.58009 , 76.192314, 75.25122 ],
       [75.56367 , 81.7986  , 78.68144 , 80.15668 , 80.48313 ]],
      dtype=float32)>

In [ ]:
# dot product
tf.tensordot(tensor_A, tf.transpose(tensor_B), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33345 , 73.40498 , 77.159615, 73.98369 , 80.90053 ],
       [75.146355, 68.80437 , 74.24302 , 71.841835, 75.60206 ],
       [79.7594  , 75.644554, 77.797585, 74.74873 , 80.559845],
       [75.08526 , 69.064064, 74.30776 , 72.27616 , 76.05669 ],
       [85.05688 , 74.26627 , 78.00687 , 74.88679 , 83.13417 ]],
      dtype=float32)>

In [ ]:
# random tensor
tf.random.set_seed(42)
random_tensor_A = tf.random.uniform(shape=(224,224,3))
random_tensor_A

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.6645621 , 0.44100678, 0.3528825 ],
        [0.46448255, 0.03366041, 0.68467236],
        [0.74011743, 0.8724445 , 0.22632635],
        ...,
        [0.42612267, 0.09686017, 0.16105258],
        [0.1487099 , 0.04513884, 0.9497483 ],
        [0.4393103 , 0.28527975, 0.96971095]],

       [[0.73308516, 0.5657046 , 0.33238935],
        [0.8838178 , 0.87544763, 0.56711245],
        [0.8879347 , 0.47661996, 0.42041814],
        ...,
        [0.7716515 , 0.9116473 , 0.3229897 ],
        [0.43050945, 0.83253574, 0.45549798],
        [0.29816985, 0.9639522 , 0.3316357 ]],

       [[0.41132426, 0.2179662 , 0.53570235],
        [0.5112119 , 0.6484759 , 0.8894886 ],
        [0.42459428, 0.20189774, 0.85781324],
        ...,
        [0.02888799, 0.3995477 , 0.11355484],
        [0.68524575, 0.04945195, 0.17778492],
        [0.97627187, 0.79811585, 0.9411576 ]],

       ...,

       [[0.9019445 , 0.27011132, 0.8090267 ],
        [0.32

In [ ]:
# minumum
tf.math.reduce_min(random_tensor_A)

<tf.Tensor: shape=(), dtype=float32, numpy=3.5762787e-07>

In [ ]:
# maximum
tf.math.reduce_max(random_tensor_A)

<tf.Tensor: shape=(), dtype=float32, numpy=0.999998>

In [ ]:
# random tensor squeezing
tf.random.set_seed(42)
inflated_tensor_A = tf.random.uniform(minval=10, maxval=100, shape=(1,224,224,3))
inflated_tensor_A

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[69.81059 , 49.69061 , 41.759426],
         [51.80343 , 13.029437, 71.620514],
         [76.610565, 88.520004, 30.369371],
         ...,
         [48.35104 , 18.717415, 24.494732],
         [23.38389 , 14.062495, 95.47735 ],
         [49.53793 , 35.67518 , 97.27399 ]],

        [[75.97766 , 60.913414, 39.915043],
         [89.5436  , 88.79028 , 61.04012 ],
         [89.91412 , 52.895798, 47.83763 ],
         ...,
         [79.44864 , 92.048256, 39.069073],
         [48.74585 , 84.928215, 50.99482 ],
         [36.83529 , 96.7557  , 39.847214]],

        [[47.019184, 29.616959, 58.21321 ],
         [56.009068, 68.36283 , 90.05397 ],
         [48.213486, 28.170797, 87.20319 ],
         ...,
         [12.599918, 45.959293, 20.219936],
         [71.67212 , 14.450675, 26.000643],
         [97.86447 , 81.83043 , 94.704185]],

        ...,

        [[91.175   , 34.31002 , 82.81241 ],
         [39.15573 , 70.05211 , 94.66057 ],


In [ ]:
tf.squeeze(inflated_tensor_A)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[69.81059 , 49.69061 , 41.759426],
        [51.80343 , 13.029437, 71.620514],
        [76.610565, 88.520004, 30.369371],
        ...,
        [48.35104 , 18.717415, 24.494732],
        [23.38389 , 14.062495, 95.47735 ],
        [49.53793 , 35.67518 , 97.27399 ]],

       [[75.97766 , 60.913414, 39.915043],
        [89.5436  , 88.79028 , 61.04012 ],
        [89.91412 , 52.895798, 47.83763 ],
        ...,
        [79.44864 , 92.048256, 39.069073],
        [48.74585 , 84.928215, 50.99482 ],
        [36.83529 , 96.7557  , 39.847214]],

       [[47.019184, 29.616959, 58.21321 ],
        [56.009068, 68.36283 , 90.05397 ],
        [48.213486, 28.170797, 87.20319 ],
        ...,
        [12.599918, 45.959293, 20.219936],
        [71.67212 , 14.450675, 26.000643],
        [97.86447 , 81.83043 , 94.704185]],

       ...,

       [[91.175   , 34.31002 , 82.81241 ],
        [39.15573 , 70.05211 , 94.66057 ],
        [74.49505 , 89.7464

In [ ]:
# random tensor of shape 10
tf.random.set_seed(42)
shape_X = tf.random.uniform(shape=(10,))
shape_X

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686],
      dtype=float32)>

In [ ]:
# max index
tf.argmax(shape_X)

<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [ ]:
tf.cast(tf.one_hot(np.arange(0,tf.size(shape_X)), depth=10), dtype=tf.int32)

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int32)>